### ISSUE TITLE
How does setting the REQUEST_URI work?

### ISSUE THREAD

**Issue by ktomk** [philwinkle/Magento-PHP-Webserver-Router#3]
The first if-branch is setting the Request URI:

```
if (preg_match('#^/api/rest#', $_SERVER["REQUEST_URI"])) {
  $_SERVER["REQUEST_URI"] = 'api.php?type=rest';
} elseif [...]
```

The script will then end after that line if the condition is true.

I couldn't find any documentation about that and wonder where this is outlined / how that works.

**Comment by surfer190** [comment]
@philwinkle Yeah, so the rest api does not work?
